### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by edwinligthart** [jeatheak/Mitsubishi-WF-RAC-Integration#25] opened 2022-10-15 08:23 UTC
Perfect add-on so far. Can you also implement the control of the left/right swing modes?

**Comment by maurits-h** [comment] 2022-10-20 17:46
Duplicate of #12

**Comment by jeatheak** [comment] 2022-10-24 11:39
@edwinligthart Thank you for the request. But this is indeed a Duplicate request. I will close this one.
At the moment I have little time but if I have time I will try to implement it.

**Closed by jeatheak** 2022-10-24 11:39 UTC
